id: amplitude_github_action_refactor
namespace: amplitude_api

tasks:
  - id: python_scripts
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/Jaffulee/deng3-amplitude
        branch: main

      - id: run_python_script
        type: io.kestra.plugin.scripts.python.Commands
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        containerImage: python:3.11-slim #shady
        beforeCommands:
          - pip install -r requirements.txt
        commands:
          - python main.py
        env:
          S3_USER_ACCESS_KEY: "{{ kv('S3_USER_ACCESS_KEY') }}"
          S3_USER_SECRET_KEY: "{{ kv('S3_USER_SECRET_KEY') }}"
          AWS_BUCKET_NAME: "{{ kv('AWS_BUCKET_NAME') }}"
          AMP_API_KEY: "{{ kv('AMP_API_KEY')}}"
          AMP_SECRET_KEY: "{{ kv('AMP_SECRET_KEY')}}"
          AMP_DATA_REGION: "{{ kv('AMP_DATA_REGION')}}"
triggers:
- id: schedule
  type: io.kestra.plugin.core.trigger.Schedule
  cron: "@hourly"


